// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: request.proto

package com.mumu.learn.grpc;

public interface AddRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.mumu.learn.grpc.AddRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string requestId = 1;</code>
   * @return The requestId.
   */
  java.lang.String getRequestId();
  /**
   * <code>string requestId = 1;</code>
   * @return The bytes for requestId.
   */
  com.google.protobuf.ByteString
      getRequestIdBytes();

  /**
   * <code>int32 a = 2;</code>
   * @return The a.
   */
  int getA();

  /**
   * <code>int32 b = 3;</code>
   * @return The b.
   */
  int getB();

  /**
   * <code>repeated int32 c = 4;</code>
   * @return A list containing the c.
   */
  java.util.List<java.lang.Integer> getCList();
  /**
   * <code>repeated int32 c = 4;</code>
   * @return The count of c.
   */
  int getCCount();
  /**
   * <code>repeated int32 c = 4;</code>
   * @param index The index of the element to return.
   * @return The c at the given index.
   */
  int getC(int index);

  /**
   * <code>map&lt;int32, int32&gt; m = 5;</code>
   */
  int getMCount();
  /**
   * <code>map&lt;int32, int32&gt; m = 5;</code>
   */
  boolean containsM(
      int key);
  /**
   * Use {@link #getMMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.Integer, java.lang.Integer>
  getM();
  /**
   * <code>map&lt;int32, int32&gt; m = 5;</code>
   */
  java.util.Map<java.lang.Integer, java.lang.Integer>
  getMMap();
  /**
   * <code>map&lt;int32, int32&gt; m = 5;</code>
   */

  int getMOrDefault(
      int key,
      int defaultValue);
  /**
   * <code>map&lt;int32, int32&gt; m = 5;</code>
   */

  int getMOrThrow(
      int key);

  /**
   * <code>.com.mumu.learn.grpc.Digits digits = 6;</code>
   * @return Whether the digits field is set.
   */
  boolean hasDigits();
  /**
   * <code>.com.mumu.learn.grpc.Digits digits = 6;</code>
   * @return The digits.
   */
  com.mumu.learn.grpc.Digits getDigits();
  /**
   * <code>.com.mumu.learn.grpc.Digits digits = 6;</code>
   */
  com.mumu.learn.grpc.DigitsOrBuilder getDigitsOrBuilder();
}
