// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: request.proto

package com.mumu.learn.grpc;

public interface AddResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.mumu.learn.grpc.AddResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string requestId = 1;</code>
   * @return The requestId.
   */
  java.lang.String getRequestId();
  /**
   * <code>string requestId = 1;</code>
   * @return The bytes for requestId.
   */
  com.google.protobuf.ByteString
      getRequestIdBytes();

  /**
   * <code>int32 res = 2;</code>
   * @return The res.
   */
  int getRes();
}
