// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: request.proto

package com.mumu.learn.grpc;

/**
 * Protobuf type {@code com.mumu.learn.grpc.AddRequest}
 */
public final class AddRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.mumu.learn.grpc.AddRequest)
    AddRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AddRequest.newBuilder() to construct.
  private AddRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AddRequest() {
    requestId_ = "";
    c_ = emptyIntList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new AddRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private AddRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            requestId_ = s;
            break;
          }
          case 16: {

            a_ = input.readInt32();
            break;
          }
          case 24: {

            b_ = input.readInt32();
            break;
          }
          case 32: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              c_ = newIntList();
              mutable_bitField0_ |= 0x00000001;
            }
            c_.addInt(input.readInt32());
            break;
          }
          case 34: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            if (!((mutable_bitField0_ & 0x00000001) != 0) && input.getBytesUntilLimit() > 0) {
              c_ = newIntList();
              mutable_bitField0_ |= 0x00000001;
            }
            while (input.getBytesUntilLimit() > 0) {
              c_.addInt(input.readInt32());
            }
            input.popLimit(limit);
            break;
          }
          case 42: {
            if (!((mutable_bitField0_ & 0x00000002) != 0)) {
              m_ = com.google.protobuf.MapField.newMapField(
                  MDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000002;
            }
            com.google.protobuf.MapEntry<java.lang.Integer, java.lang.Integer>
            m__ = input.readMessage(
                MDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            m_.getMutableMap().put(
                m__.getKey(), m__.getValue());
            break;
          }
          case 50: {
            com.mumu.learn.grpc.Digits.Builder subBuilder = null;
            if (digits_ != null) {
              subBuilder = digits_.toBuilder();
            }
            digits_ = input.readMessage(com.mumu.learn.grpc.Digits.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(digits_);
              digits_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        c_.makeImmutable(); // C
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.mumu.learn.grpc.MuMuServer.internal_static_com_mumu_learn_grpc_AddRequest_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 5:
        return internalGetM();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.mumu.learn.grpc.MuMuServer.internal_static_com_mumu_learn_grpc_AddRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.mumu.learn.grpc.AddRequest.class, com.mumu.learn.grpc.AddRequest.Builder.class);
  }

  public static final int REQUESTID_FIELD_NUMBER = 1;
  private volatile java.lang.Object requestId_;
  /**
   * <code>string requestId = 1;</code>
   * @return The requestId.
   */
  @java.lang.Override
  public java.lang.String getRequestId() {
    java.lang.Object ref = requestId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      requestId_ = s;
      return s;
    }
  }
  /**
   * <code>string requestId = 1;</code>
   * @return The bytes for requestId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRequestIdBytes() {
    java.lang.Object ref = requestId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      requestId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int A_FIELD_NUMBER = 2;
  private int a_;
  /**
   * <code>int32 a = 2;</code>
   * @return The a.
   */
  @java.lang.Override
  public int getA() {
    return a_;
  }

  public static final int B_FIELD_NUMBER = 3;
  private int b_;
  /**
   * <code>int32 b = 3;</code>
   * @return The b.
   */
  @java.lang.Override
  public int getB() {
    return b_;
  }

  public static final int C_FIELD_NUMBER = 4;
  private com.google.protobuf.Internal.IntList c_;
  /**
   * <code>repeated int32 c = 4;</code>
   * @return A list containing the c.
   */
  @java.lang.Override
  public java.util.List<java.lang.Integer>
      getCList() {
    return c_;
  }
  /**
   * <code>repeated int32 c = 4;</code>
   * @return The count of c.
   */
  public int getCCount() {
    return c_.size();
  }
  /**
   * <code>repeated int32 c = 4;</code>
   * @param index The index of the element to return.
   * @return The c at the given index.
   */
  public int getC(int index) {
    return c_.getInt(index);
  }
  private int cMemoizedSerializedSize = -1;

  public static final int M_FIELD_NUMBER = 5;
  private static final class MDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.Integer, java.lang.Integer> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.Integer, java.lang.Integer>newDefaultInstance(
                com.mumu.learn.grpc.MuMuServer.internal_static_com_mumu_learn_grpc_AddRequest_MEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.INT32,
                0,
                com.google.protobuf.WireFormat.FieldType.INT32,
                0);
  }
  private com.google.protobuf.MapField<
      java.lang.Integer, java.lang.Integer> m_;
  private com.google.protobuf.MapField<java.lang.Integer, java.lang.Integer>
  internalGetM() {
    if (m_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          MDefaultEntryHolder.defaultEntry);
    }
    return m_;
  }

  public int getMCount() {
    return internalGetM().getMap().size();
  }
  /**
   * <code>map&lt;int32, int32&gt; m = 5;</code>
   */

  @java.lang.Override
  public boolean containsM(
      int key) {
    
    return internalGetM().getMap().containsKey(key);
  }
  /**
   * Use {@link #getMMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.Integer, java.lang.Integer> getM() {
    return getMMap();
  }
  /**
   * <code>map&lt;int32, int32&gt; m = 5;</code>
   */
  @java.lang.Override

  public java.util.Map<java.lang.Integer, java.lang.Integer> getMMap() {
    return internalGetM().getMap();
  }
  /**
   * <code>map&lt;int32, int32&gt; m = 5;</code>
   */
  @java.lang.Override

  public int getMOrDefault(
      int key,
      int defaultValue) {
    
    java.util.Map<java.lang.Integer, java.lang.Integer> map =
        internalGetM().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;int32, int32&gt; m = 5;</code>
   */
  @java.lang.Override

  public int getMOrThrow(
      int key) {
    
    java.util.Map<java.lang.Integer, java.lang.Integer> map =
        internalGetM().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  public static final int DIGITS_FIELD_NUMBER = 6;
  private com.mumu.learn.grpc.Digits digits_;
  /**
   * <code>.com.mumu.learn.grpc.Digits digits = 6;</code>
   * @return Whether the digits field is set.
   */
  @java.lang.Override
  public boolean hasDigits() {
    return digits_ != null;
  }
  /**
   * <code>.com.mumu.learn.grpc.Digits digits = 6;</code>
   * @return The digits.
   */
  @java.lang.Override
  public com.mumu.learn.grpc.Digits getDigits() {
    return digits_ == null ? com.mumu.learn.grpc.Digits.getDefaultInstance() : digits_;
  }
  /**
   * <code>.com.mumu.learn.grpc.Digits digits = 6;</code>
   */
  @java.lang.Override
  public com.mumu.learn.grpc.DigitsOrBuilder getDigitsOrBuilder() {
    return getDigits();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (!getRequestIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, requestId_);
    }
    if (a_ != 0) {
      output.writeInt32(2, a_);
    }
    if (b_ != 0) {
      output.writeInt32(3, b_);
    }
    if (getCList().size() > 0) {
      output.writeUInt32NoTag(34);
      output.writeUInt32NoTag(cMemoizedSerializedSize);
    }
    for (int i = 0; i < c_.size(); i++) {
      output.writeInt32NoTag(c_.getInt(i));
    }
    com.google.protobuf.GeneratedMessageV3
      .serializeIntegerMapTo(
        output,
        internalGetM(),
        MDefaultEntryHolder.defaultEntry,
        5);
    if (digits_ != null) {
      output.writeMessage(6, getDigits());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getRequestIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, requestId_);
    }
    if (a_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, a_);
    }
    if (b_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, b_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < c_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeInt32SizeNoTag(c_.getInt(i));
      }
      size += dataSize;
      if (!getCList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      cMemoizedSerializedSize = dataSize;
    }
    for (java.util.Map.Entry<java.lang.Integer, java.lang.Integer> entry
         : internalGetM().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.Integer, java.lang.Integer>
      m__ = MDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, m__);
    }
    if (digits_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getDigits());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.mumu.learn.grpc.AddRequest)) {
      return super.equals(obj);
    }
    com.mumu.learn.grpc.AddRequest other = (com.mumu.learn.grpc.AddRequest) obj;

    if (!getRequestId()
        .equals(other.getRequestId())) return false;
    if (getA()
        != other.getA()) return false;
    if (getB()
        != other.getB()) return false;
    if (!getCList()
        .equals(other.getCList())) return false;
    if (!internalGetM().equals(
        other.internalGetM())) return false;
    if (hasDigits() != other.hasDigits()) return false;
    if (hasDigits()) {
      if (!getDigits()
          .equals(other.getDigits())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + REQUESTID_FIELD_NUMBER;
    hash = (53 * hash) + getRequestId().hashCode();
    hash = (37 * hash) + A_FIELD_NUMBER;
    hash = (53 * hash) + getA();
    hash = (37 * hash) + B_FIELD_NUMBER;
    hash = (53 * hash) + getB();
    if (getCCount() > 0) {
      hash = (37 * hash) + C_FIELD_NUMBER;
      hash = (53 * hash) + getCList().hashCode();
    }
    if (!internalGetM().getMap().isEmpty()) {
      hash = (37 * hash) + M_FIELD_NUMBER;
      hash = (53 * hash) + internalGetM().hashCode();
    }
    if (hasDigits()) {
      hash = (37 * hash) + DIGITS_FIELD_NUMBER;
      hash = (53 * hash) + getDigits().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.mumu.learn.grpc.AddRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.mumu.learn.grpc.AddRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.mumu.learn.grpc.AddRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.mumu.learn.grpc.AddRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.mumu.learn.grpc.AddRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.mumu.learn.grpc.AddRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.mumu.learn.grpc.AddRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.mumu.learn.grpc.AddRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.mumu.learn.grpc.AddRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.mumu.learn.grpc.AddRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.mumu.learn.grpc.AddRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.mumu.learn.grpc.AddRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.mumu.learn.grpc.AddRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.mumu.learn.grpc.AddRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.mumu.learn.grpc.AddRequest)
      com.mumu.learn.grpc.AddRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mumu.learn.grpc.MuMuServer.internal_static_com_mumu_learn_grpc_AddRequest_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 5:
          return internalGetM();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 5:
          return internalGetMutableM();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mumu.learn.grpc.MuMuServer.internal_static_com_mumu_learn_grpc_AddRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mumu.learn.grpc.AddRequest.class, com.mumu.learn.grpc.AddRequest.Builder.class);
    }

    // Construct using com.mumu.learn.grpc.AddRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      requestId_ = "";

      a_ = 0;

      b_ = 0;

      c_ = emptyIntList();
      bitField0_ = (bitField0_ & ~0x00000001);
      internalGetMutableM().clear();
      if (digitsBuilder_ == null) {
        digits_ = null;
      } else {
        digits_ = null;
        digitsBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.mumu.learn.grpc.MuMuServer.internal_static_com_mumu_learn_grpc_AddRequest_descriptor;
    }

    @java.lang.Override
    public com.mumu.learn.grpc.AddRequest getDefaultInstanceForType() {
      return com.mumu.learn.grpc.AddRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.mumu.learn.grpc.AddRequest build() {
      com.mumu.learn.grpc.AddRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.mumu.learn.grpc.AddRequest buildPartial() {
      com.mumu.learn.grpc.AddRequest result = new com.mumu.learn.grpc.AddRequest(this);
      int from_bitField0_ = bitField0_;
      result.requestId_ = requestId_;
      result.a_ = a_;
      result.b_ = b_;
      if (((bitField0_ & 0x00000001) != 0)) {
        c_.makeImmutable();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.c_ = c_;
      result.m_ = internalGetM();
      result.m_.makeImmutable();
      if (digitsBuilder_ == null) {
        result.digits_ = digits_;
      } else {
        result.digits_ = digitsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.mumu.learn.grpc.AddRequest) {
        return mergeFrom((com.mumu.learn.grpc.AddRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.mumu.learn.grpc.AddRequest other) {
      if (other == com.mumu.learn.grpc.AddRequest.getDefaultInstance()) return this;
      if (!other.getRequestId().isEmpty()) {
        requestId_ = other.requestId_;
        onChanged();
      }
      if (other.getA() != 0) {
        setA(other.getA());
      }
      if (other.getB() != 0) {
        setB(other.getB());
      }
      if (!other.c_.isEmpty()) {
        if (c_.isEmpty()) {
          c_ = other.c_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureCIsMutable();
          c_.addAll(other.c_);
        }
        onChanged();
      }
      internalGetMutableM().mergeFrom(
          other.internalGetM());
      if (other.hasDigits()) {
        mergeDigits(other.getDigits());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.mumu.learn.grpc.AddRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.mumu.learn.grpc.AddRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object requestId_ = "";
    /**
     * <code>string requestId = 1;</code>
     * @return The requestId.
     */
    public java.lang.String getRequestId() {
      java.lang.Object ref = requestId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        requestId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string requestId = 1;</code>
     * @return The bytes for requestId.
     */
    public com.google.protobuf.ByteString
        getRequestIdBytes() {
      java.lang.Object ref = requestId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        requestId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string requestId = 1;</code>
     * @param value The requestId to set.
     * @return This builder for chaining.
     */
    public Builder setRequestId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      requestId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string requestId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearRequestId() {
      
      requestId_ = getDefaultInstance().getRequestId();
      onChanged();
      return this;
    }
    /**
     * <code>string requestId = 1;</code>
     * @param value The bytes for requestId to set.
     * @return This builder for chaining.
     */
    public Builder setRequestIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      requestId_ = value;
      onChanged();
      return this;
    }

    private int a_ ;
    /**
     * <code>int32 a = 2;</code>
     * @return The a.
     */
    @java.lang.Override
    public int getA() {
      return a_;
    }
    /**
     * <code>int32 a = 2;</code>
     * @param value The a to set.
     * @return This builder for chaining.
     */
    public Builder setA(int value) {
      
      a_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 a = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearA() {
      
      a_ = 0;
      onChanged();
      return this;
    }

    private int b_ ;
    /**
     * <code>int32 b = 3;</code>
     * @return The b.
     */
    @java.lang.Override
    public int getB() {
      return b_;
    }
    /**
     * <code>int32 b = 3;</code>
     * @param value The b to set.
     * @return This builder for chaining.
     */
    public Builder setB(int value) {
      
      b_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 b = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearB() {
      
      b_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.Internal.IntList c_ = emptyIntList();
    private void ensureCIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        c_ = mutableCopy(c_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated int32 c = 4;</code>
     * @return A list containing the c.
     */
    public java.util.List<java.lang.Integer>
        getCList() {
      return ((bitField0_ & 0x00000001) != 0) ?
               java.util.Collections.unmodifiableList(c_) : c_;
    }
    /**
     * <code>repeated int32 c = 4;</code>
     * @return The count of c.
     */
    public int getCCount() {
      return c_.size();
    }
    /**
     * <code>repeated int32 c = 4;</code>
     * @param index The index of the element to return.
     * @return The c at the given index.
     */
    public int getC(int index) {
      return c_.getInt(index);
    }
    /**
     * <code>repeated int32 c = 4;</code>
     * @param index The index to set the value at.
     * @param value The c to set.
     * @return This builder for chaining.
     */
    public Builder setC(
        int index, int value) {
      ensureCIsMutable();
      c_.setInt(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 c = 4;</code>
     * @param value The c to add.
     * @return This builder for chaining.
     */
    public Builder addC(int value) {
      ensureCIsMutable();
      c_.addInt(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 c = 4;</code>
     * @param values The c to add.
     * @return This builder for chaining.
     */
    public Builder addAllC(
        java.lang.Iterable<? extends java.lang.Integer> values) {
      ensureCIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, c_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 c = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearC() {
      c_ = emptyIntList();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }

    private com.google.protobuf.MapField<
        java.lang.Integer, java.lang.Integer> m_;
    private com.google.protobuf.MapField<java.lang.Integer, java.lang.Integer>
    internalGetM() {
      if (m_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            MDefaultEntryHolder.defaultEntry);
      }
      return m_;
    }
    private com.google.protobuf.MapField<java.lang.Integer, java.lang.Integer>
    internalGetMutableM() {
      onChanged();;
      if (m_ == null) {
        m_ = com.google.protobuf.MapField.newMapField(
            MDefaultEntryHolder.defaultEntry);
      }
      if (!m_.isMutable()) {
        m_ = m_.copy();
      }
      return m_;
    }

    public int getMCount() {
      return internalGetM().getMap().size();
    }
    /**
     * <code>map&lt;int32, int32&gt; m = 5;</code>
     */

    @java.lang.Override
    public boolean containsM(
        int key) {
      
      return internalGetM().getMap().containsKey(key);
    }
    /**
     * Use {@link #getMMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.Integer, java.lang.Integer> getM() {
      return getMMap();
    }
    /**
     * <code>map&lt;int32, int32&gt; m = 5;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.Integer, java.lang.Integer> getMMap() {
      return internalGetM().getMap();
    }
    /**
     * <code>map&lt;int32, int32&gt; m = 5;</code>
     */
    @java.lang.Override

    public int getMOrDefault(
        int key,
        int defaultValue) {
      
      java.util.Map<java.lang.Integer, java.lang.Integer> map =
          internalGetM().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;int32, int32&gt; m = 5;</code>
     */
    @java.lang.Override

    public int getMOrThrow(
        int key) {
      
      java.util.Map<java.lang.Integer, java.lang.Integer> map =
          internalGetM().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearM() {
      internalGetMutableM().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;int32, int32&gt; m = 5;</code>
     */

    public Builder removeM(
        int key) {
      
      internalGetMutableM().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.Integer, java.lang.Integer>
    getMutableM() {
      return internalGetMutableM().getMutableMap();
    }
    /**
     * <code>map&lt;int32, int32&gt; m = 5;</code>
     */
    public Builder putM(
        int key,
        int value) {
      
      
      internalGetMutableM().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <code>map&lt;int32, int32&gt; m = 5;</code>
     */

    public Builder putAllM(
        java.util.Map<java.lang.Integer, java.lang.Integer> values) {
      internalGetMutableM().getMutableMap()
          .putAll(values);
      return this;
    }

    private com.mumu.learn.grpc.Digits digits_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.mumu.learn.grpc.Digits, com.mumu.learn.grpc.Digits.Builder, com.mumu.learn.grpc.DigitsOrBuilder> digitsBuilder_;
    /**
     * <code>.com.mumu.learn.grpc.Digits digits = 6;</code>
     * @return Whether the digits field is set.
     */
    public boolean hasDigits() {
      return digitsBuilder_ != null || digits_ != null;
    }
    /**
     * <code>.com.mumu.learn.grpc.Digits digits = 6;</code>
     * @return The digits.
     */
    public com.mumu.learn.grpc.Digits getDigits() {
      if (digitsBuilder_ == null) {
        return digits_ == null ? com.mumu.learn.grpc.Digits.getDefaultInstance() : digits_;
      } else {
        return digitsBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.mumu.learn.grpc.Digits digits = 6;</code>
     */
    public Builder setDigits(com.mumu.learn.grpc.Digits value) {
      if (digitsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        digits_ = value;
        onChanged();
      } else {
        digitsBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.com.mumu.learn.grpc.Digits digits = 6;</code>
     */
    public Builder setDigits(
        com.mumu.learn.grpc.Digits.Builder builderForValue) {
      if (digitsBuilder_ == null) {
        digits_ = builderForValue.build();
        onChanged();
      } else {
        digitsBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.com.mumu.learn.grpc.Digits digits = 6;</code>
     */
    public Builder mergeDigits(com.mumu.learn.grpc.Digits value) {
      if (digitsBuilder_ == null) {
        if (digits_ != null) {
          digits_ =
            com.mumu.learn.grpc.Digits.newBuilder(digits_).mergeFrom(value).buildPartial();
        } else {
          digits_ = value;
        }
        onChanged();
      } else {
        digitsBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.com.mumu.learn.grpc.Digits digits = 6;</code>
     */
    public Builder clearDigits() {
      if (digitsBuilder_ == null) {
        digits_ = null;
        onChanged();
      } else {
        digits_ = null;
        digitsBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.com.mumu.learn.grpc.Digits digits = 6;</code>
     */
    public com.mumu.learn.grpc.Digits.Builder getDigitsBuilder() {
      
      onChanged();
      return getDigitsFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.mumu.learn.grpc.Digits digits = 6;</code>
     */
    public com.mumu.learn.grpc.DigitsOrBuilder getDigitsOrBuilder() {
      if (digitsBuilder_ != null) {
        return digitsBuilder_.getMessageOrBuilder();
      } else {
        return digits_ == null ?
            com.mumu.learn.grpc.Digits.getDefaultInstance() : digits_;
      }
    }
    /**
     * <code>.com.mumu.learn.grpc.Digits digits = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.mumu.learn.grpc.Digits, com.mumu.learn.grpc.Digits.Builder, com.mumu.learn.grpc.DigitsOrBuilder> 
        getDigitsFieldBuilder() {
      if (digitsBuilder_ == null) {
        digitsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.mumu.learn.grpc.Digits, com.mumu.learn.grpc.Digits.Builder, com.mumu.learn.grpc.DigitsOrBuilder>(
                getDigits(),
                getParentForChildren(),
                isClean());
        digits_ = null;
      }
      return digitsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.mumu.learn.grpc.AddRequest)
  }

  // @@protoc_insertion_point(class_scope:com.mumu.learn.grpc.AddRequest)
  private static final com.mumu.learn.grpc.AddRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.mumu.learn.grpc.AddRequest();
  }

  public static com.mumu.learn.grpc.AddRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AddRequest>
      PARSER = new com.google.protobuf.AbstractParser<AddRequest>() {
    @java.lang.Override
    public AddRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new AddRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AddRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AddRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.mumu.learn.grpc.AddRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

