// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: request.proto

package com.mumu.learn.grpc;

public interface DigitsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.mumu.learn.grpc.Digits)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 d = 1;</code>
   * @return The d.
   */
  int getD();

  /**
   * <code>int32 e = 2;</code>
   * @return The e.
   */
  int getE();
}
