// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: request.proto

package com.mumu.learn.grpc;

/**
 * Protobuf type {@code com.mumu.learn.grpc.Digits}
 */
public final class Digits extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.mumu.learn.grpc.Digits)
    DigitsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Digits.newBuilder() to construct.
  private Digits(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Digits() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Digits();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Digits(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            d_ = input.readInt32();
            break;
          }
          case 16: {

            e_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.mumu.learn.grpc.MuMuServer.internal_static_com_mumu_learn_grpc_Digits_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.mumu.learn.grpc.MuMuServer.internal_static_com_mumu_learn_grpc_Digits_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.mumu.learn.grpc.Digits.class, com.mumu.learn.grpc.Digits.Builder.class);
  }

  public static final int D_FIELD_NUMBER = 1;
  private int d_;
  /**
   * <code>int32 d = 1;</code>
   * @return The d.
   */
  @java.lang.Override
  public int getD() {
    return d_;
  }

  public static final int E_FIELD_NUMBER = 2;
  private int e_;
  /**
   * <code>int32 e = 2;</code>
   * @return The e.
   */
  @java.lang.Override
  public int getE() {
    return e_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (d_ != 0) {
      output.writeInt32(1, d_);
    }
    if (e_ != 0) {
      output.writeInt32(2, e_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (d_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, d_);
    }
    if (e_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, e_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.mumu.learn.grpc.Digits)) {
      return super.equals(obj);
    }
    com.mumu.learn.grpc.Digits other = (com.mumu.learn.grpc.Digits) obj;

    if (getD()
        != other.getD()) return false;
    if (getE()
        != other.getE()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + D_FIELD_NUMBER;
    hash = (53 * hash) + getD();
    hash = (37 * hash) + E_FIELD_NUMBER;
    hash = (53 * hash) + getE();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.mumu.learn.grpc.Digits parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.mumu.learn.grpc.Digits parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.mumu.learn.grpc.Digits parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.mumu.learn.grpc.Digits parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.mumu.learn.grpc.Digits parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.mumu.learn.grpc.Digits parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.mumu.learn.grpc.Digits parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.mumu.learn.grpc.Digits parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.mumu.learn.grpc.Digits parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.mumu.learn.grpc.Digits parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.mumu.learn.grpc.Digits parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.mumu.learn.grpc.Digits parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.mumu.learn.grpc.Digits prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.mumu.learn.grpc.Digits}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.mumu.learn.grpc.Digits)
      com.mumu.learn.grpc.DigitsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mumu.learn.grpc.MuMuServer.internal_static_com_mumu_learn_grpc_Digits_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mumu.learn.grpc.MuMuServer.internal_static_com_mumu_learn_grpc_Digits_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mumu.learn.grpc.Digits.class, com.mumu.learn.grpc.Digits.Builder.class);
    }

    // Construct using com.mumu.learn.grpc.Digits.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      d_ = 0;

      e_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.mumu.learn.grpc.MuMuServer.internal_static_com_mumu_learn_grpc_Digits_descriptor;
    }

    @java.lang.Override
    public com.mumu.learn.grpc.Digits getDefaultInstanceForType() {
      return com.mumu.learn.grpc.Digits.getDefaultInstance();
    }

    @java.lang.Override
    public com.mumu.learn.grpc.Digits build() {
      com.mumu.learn.grpc.Digits result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.mumu.learn.grpc.Digits buildPartial() {
      com.mumu.learn.grpc.Digits result = new com.mumu.learn.grpc.Digits(this);
      result.d_ = d_;
      result.e_ = e_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.mumu.learn.grpc.Digits) {
        return mergeFrom((com.mumu.learn.grpc.Digits)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.mumu.learn.grpc.Digits other) {
      if (other == com.mumu.learn.grpc.Digits.getDefaultInstance()) return this;
      if (other.getD() != 0) {
        setD(other.getD());
      }
      if (other.getE() != 0) {
        setE(other.getE());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.mumu.learn.grpc.Digits parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.mumu.learn.grpc.Digits) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int d_ ;
    /**
     * <code>int32 d = 1;</code>
     * @return The d.
     */
    @java.lang.Override
    public int getD() {
      return d_;
    }
    /**
     * <code>int32 d = 1;</code>
     * @param value The d to set.
     * @return This builder for chaining.
     */
    public Builder setD(int value) {
      
      d_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 d = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearD() {
      
      d_ = 0;
      onChanged();
      return this;
    }

    private int e_ ;
    /**
     * <code>int32 e = 2;</code>
     * @return The e.
     */
    @java.lang.Override
    public int getE() {
      return e_;
    }
    /**
     * <code>int32 e = 2;</code>
     * @param value The e to set.
     * @return This builder for chaining.
     */
    public Builder setE(int value) {
      
      e_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 e = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearE() {
      
      e_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.mumu.learn.grpc.Digits)
  }

  // @@protoc_insertion_point(class_scope:com.mumu.learn.grpc.Digits)
  private static final com.mumu.learn.grpc.Digits DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.mumu.learn.grpc.Digits();
  }

  public static com.mumu.learn.grpc.Digits getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Digits>
      PARSER = new com.google.protobuf.AbstractParser<Digits>() {
    @java.lang.Override
    public Digits parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Digits(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Digits> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Digits> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.mumu.learn.grpc.Digits getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

