// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: request.proto

package com.mumu.learn.grpc;

public final class MuMuServer {
  private MuMuServer() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_mumu_learn_grpc_AddRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_mumu_learn_grpc_AddRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_mumu_learn_grpc_AddRequest_MEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_mumu_learn_grpc_AddRequest_MEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_mumu_learn_grpc_Digits_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_mumu_learn_grpc_Digits_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_mumu_learn_grpc_AddResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_mumu_learn_grpc_AddResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rrequest.proto\022\023com.mumu.learn.grpc\"\312\001\n" +
      "\nAddRequest\022\021\n\trequestId\030\001 \001(\t\022\t\n\001a\030\002 \001(" +
      "\005\022\t\n\001b\030\003 \001(\005\022\t\n\001c\030\004 \003(\005\0221\n\001m\030\005 \003(\0132&.com" +
      ".mumu.learn.grpc.AddRequest.MEntry\022+\n\006di" +
      "gits\030\006 \001(\0132\033.com.mumu.learn.grpc.Digits\032" +
      "(\n\006MEntry\022\013\n\003key\030\001 \001(\005\022\r\n\005value\030\002 \001(\005:\0028" +
      "\001\"\036\n\006Digits\022\t\n\001d\030\001 \001(\005\022\t\n\001e\030\002 \001(\005\"-\n\013Add" +
      "Response\022\021\n\trequestId\030\001 \001(\t\022\013\n\003res\030\002 \001(\005" +
      "2X\n\nAddService\022J\n\003add\022\037.com.mumu.learn.g" +
      "rpc.AddRequest\032 .com.mumu.learn.grpc.Add" +
      "Response\"\000B#\n\023com.mumu.learn.grpcB\nMuMuS" +
      "erverP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_mumu_learn_grpc_AddRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_mumu_learn_grpc_AddRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_mumu_learn_grpc_AddRequest_descriptor,
        new java.lang.String[] { "RequestId", "A", "B", "C", "M", "Digits", });
    internal_static_com_mumu_learn_grpc_AddRequest_MEntry_descriptor =
      internal_static_com_mumu_learn_grpc_AddRequest_descriptor.getNestedTypes().get(0);
    internal_static_com_mumu_learn_grpc_AddRequest_MEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_mumu_learn_grpc_AddRequest_MEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_com_mumu_learn_grpc_Digits_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_mumu_learn_grpc_Digits_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_mumu_learn_grpc_Digits_descriptor,
        new java.lang.String[] { "D", "E", });
    internal_static_com_mumu_learn_grpc_AddResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_mumu_learn_grpc_AddResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_mumu_learn_grpc_AddResponse_descriptor,
        new java.lang.String[] { "RequestId", "Res", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
